# Site settings
title: SLON
email: musicalslon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the website of the band Slon

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.slonmusic.com/" # the base hostname & protocol for your site
soundcloud: "http://www.soundcloud.com/slon-1"

#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
